version: "3.7"

services:
  chat-ui:
    container_name: chat-ui-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
